name: Raspberry Pi Cross Compiler

on:
  push:
    branches:
      - main

jobs:
  build_compiler:
    name: Build Compiler
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Install Pre-Requisites
        run: make install-prerequisites
      - name: Build Compiler
        run: make build-compiler