name: Raspberry Pi Cross Compiler

on:
  push:
    branches:
      - main

jobs:
  build_compiler:
    name: Build Compiler
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Install Pre-Requisites
        # run: make install-prerequisites
        run: echo "none."
      - name: Build Compiler
        run: make build-compiler
      - uses: actions/upload-artifact@v4
        with:
          path: ./build/out/*.tar.gz
          name: compiler

  build_image:
    name: Build Docker Image
    runs-on: self-hosted
    needs: build_compiler
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/download-artifact@v2
        with:
          name: compiler
      - name: Unpack Compiler
        run: mkdir -p build && mkdir -p build/out && tar -xvf ./compiler/*.tar.gz -C build/out
      - name: Build Docker Image
        run: make build-image
      - name: Push Docker Image
        run: make push-image